import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// safetyRating notes:
// - Values with a real GNCAP/Global NCAP test result are marked "GNCAP tested".
// - Values without an official Indian-spec result are conservative estimates (2.0-3.0),
//   marked "estimated" — flag these for review if you get real test data later.
// - All values are written as explicit floats (4.0, not 4) to keep the column
//   type-stable across the dataset.

const cars = [
  // ---------------------- BUDGET SEGMENT (₹5L–₹12L) ----------------------
  {
    make: "Maruti Suzuki",
    model: "Swift",
    year: 2024,
    priceMin: 649000,
    priceMax: 902000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 22.4,
    safetyRating: 2.0, // GNCAP tested (2024 retest, 2-star adult)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Manual AC", category: "comfort" },
      { name: "Adjustable Driver Seat Height", category: "comfort" },
      { name: "7-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Steering Mounted Controls", category: "tech" },
    ]),
  },
  {
    make: "Hyundai",
    model: "Grand i10 Nios",
    year: 2024,
    priceMin: 575000,
    priceMax: 880000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 20.3,
    safetyRating: 2.0, // estimated
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "Manual AC", category: "comfort" },
      { name: "8-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Steering Mounted Controls", category: "tech" },
    ]),
  },
  {
    make: "Tata",
    model: "Tiago iCNG",
    year: 2024,
    priceMin: 656000,
    priceMax: 853000,
    bodyType: "HATCHBACK",
    fuelType: "CNG",
    seatingCapacity: 5,
    mileage: 26.5, // km/kg for CNG variant
    safetyRating: 4.0, // GNCAP tested (4-star adult, 2020)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Manual AC", category: "comfort" },
      { name: "Height Adjustable Driver Seat", category: "comfort" },
      { name: "7-inch Touchscreen", category: "tech" },
      { name: "Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Maruti Suzuki",
    model: "Baleno",
    year: 2024,
    priceMin: 679000,
    priceMax: 989000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 22.35,
    safetyRating: 2.0, // estimated
    suitedFor: "CITY_COMMUTE,FAMILY,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Rear Parking Camera", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Cruise Control", category: "comfort" },
      { name: "9-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Head-Up Display", category: "tech" },
    ]),
  },
  {
    make: "Honda",
    model: "Amaze",
    year: 2024,
    priceMin: 799000,
    priceMax: 1199000,
    bodyType: "SEDAN",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 18.6,
    safetyRating: 3.0, // estimated
    suitedFor: "CITY_COMMUTE,FIRST_CAR,FAMILY",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Rear AC Vents", category: "comfort" },
      { name: "7-inch Touchscreen", category: "tech" },
      { name: "Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Hyundai",
    model: "Venue",
    year: 2024,
    priceMin: 799000,
    priceMax: 1399000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 18.2,
    safetyRating: 5.0, // GNCAP tested (2024, 5-star adult)
    suitedFor: "CITY_COMMUTE,FAMILY,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Rear Parking Camera", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "BlueLink Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Maruti Suzuki",
    model: "Brezza",
    year: 2024,
    priceMin: 839000,
    priceMax: 1399000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 19.8,
    safetyRating: 4.0, // GNCAP tested (2024 retest, 4-star adult)
    suitedFor: "CITY_COMMUTE,FAMILY",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "9-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Head-Up Display", category: "tech" },
    ]),
  },
  {
    make: "Maruti Suzuki",
    model: "Dzire",
    year: 2024,
    priceMin: 699000,
    priceMax: 999000,
    bodyType: "SEDAN",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 24.79,
    safetyRating: 4.0, // GNCAP tested (2024 model, 4-star adult)
    suitedFor: "CITY_COMMUTE,FIRST_CAR,FAMILY",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "9-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Tata",
    model: "Punch",
    year: 2024,
    priceMin: 599000,
    priceMax: 999000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 20.09,
    safetyRating: 5.0, // GNCAP tested (2021, 5-star adult)
    suitedFor: "CITY_COMMUTE,FAMILY,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "Manual AC", category: "comfort" },
      { name: "Height Adjustable Driver Seat", category: "comfort" },
      { name: "7-inch Touchscreen", category: "tech" },
      { name: "Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Hyundai",
    model: "i20",
    year: 2024,
    priceMin: 799000,
    priceMax: 1199000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 20.0,
    safetyRating: 2.0, // estimated
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Bose Sound System", category: "tech" },
    ]),
  },
  {
    make: "Renault",
    model: "Kwid",
    year: 2024,
    priceMin: 469000,
    priceMax: 689000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 22.0,
    safetyRating: 1.0, // GNCAP tested (1-star adult, retested)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Manual AC", category: "comfort" },
      { name: "8-inch Touchscreen", category: "tech" },
      { name: "Android Auto/CarPlay", category: "tech" },
      { name: "Digital Instrument Cluster", category: "tech" },
    ]),
  },

  // ---------------------- MID SEGMENT (₹12L–₹25L) ----------------------
  {
    make: "Hyundai",
    model: "Creta",
    year: 2024,
    priceMin: 1110000,
    priceMax: 2010000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 16.8,
    safetyRating: 3.0, // GNCAP tested (2023, 3-star adult)
    suitedFor: "FAMILY,CITY_COMMUTE,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Auto AC with Rear Vents", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Bose Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "BlueLink Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Kia",
    model: "Seltos",
    year: 2024,
    priceMin: 1090000,
    priceMax: 2020000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 16.5,
    safetyRating: 3.0, // estimated
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Bose Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "UVO Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Tata",
    model: "Nexon",
    year: 2024,
    priceMin: 800000,
    priceMax: 1560000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 17.4,
    safetyRating: 5.0, // GNCAP tested (2018, 5-star adult, benchmark result)
    suitedFor: "CITY_COMMUTE,FAMILY,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "Auto AC", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "JBL Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Honda",
    model: "City",
    year: 2024,
    priceMin: 1199000,
    priceMax: 1599000,
    bodyType: "SEDAN",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 18.4,
    safetyRating: 3.0, // estimated
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Auto AC with Rear Vents", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "8-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Maruti Suzuki",
    model: "Ciaz",
    year: 2024,
    priceMin: 1199000,
    priceMax: 1399000,
    bodyType: "SEDAN",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 20.01,
    safetyRating: 2.0, // estimated
    suitedFor: "FAMILY,CITY_COMMUTE",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "Auto AC with Rear Vents", category: "comfort" },
      { name: "Leatherette Seats", category: "comfort" },
      { name: "7-inch Touchscreen", category: "tech" },
      { name: "Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Volkswagen",
    model: "Taigun",
    year: 2024,
    priceMin: 1199000,
    priceMax: 1999000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 18.5,
    safetyRating: 5.0, // GNCAP tested (2022, 5-star adult)
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Hold Control", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "Wireless Charging", category: "comfort" },
      { name: "10-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Digital Cockpit", category: "tech" },
    ]),
  },
  {
    make: "Skoda",
    model: "Kushaq",
    year: 2024,
    priceMin: 1199000,
    priceMax: 1999000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 18.5,
    safetyRating: 5.0, // GNCAP tested (2022, 5-star adult, shared platform with Taigun)
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Hold Control", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "Wireless Charging", category: "comfort" },
      { name: "10-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Digital Cockpit", category: "tech" },
    ]),
  },
  {
    make: "Tata",
    model: "Harrier",
    year: 2024,
    priceMin: 1549000,
    priceMax: 2649000,
    bodyType: "SUV",
    fuelType: "DIESEL",
    seatingCapacity: 5,
    mileage: 16.8,
    safetyRating: 5.0, // GNCAP tested (2020, 5-star adult)
    suitedFor: "FAMILY,HIGHWAY_TOURING,OFFROAD",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Auto AC with Rear Vents", category: "comfort" },
      { name: "12.3-inch Touchscreen", category: "tech" },
      { name: "JBL Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Mahindra",
    model: "XUV700",
    year: 2024,
    priceMin: 1399000,
    priceMax: 2599000,
    bodyType: "SUV",
    fuelType: "DIESEL",
    seatingCapacity: 7,
    mileage: 16.5,
    safetyRating: 5.0, // GNCAP tested (2021, 5-star adult)
    suitedFor: "FAMILY,HIGHWAY_TOURING,OFFROAD",
    featuresJson: JSON.stringify([
      { name: "7 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Blind View Monitor", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "3-Zone Auto AC", category: "comfort" },
      { name: "Dual 10.25-inch Screens", category: "tech" },
      { name: "Sony 3D Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "AdrenoX Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Toyota",
    model: "Urban Cruiser Hyryder",
    year: 2024,
    priceMin: 1115000,
    priceMax: 1999000,
    bodyType: "SUV",
    fuelType: "HYBRID",
    seatingCapacity: 5,
    mileage: 27.97,
    safetyRating: 3.0, // estimated
    suitedFor: "CITY_COMMUTE,FAMILY",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Hold Control", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "9-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Head-Up Display", category: "tech" },
    ]),
  },

  // ---------------------- PREMIUM SEGMENT (₹25L+) ----------------------
  {
    make: "MG",
    model: "Hector",
    year: 2024,
    priceMin: 1399000,
    priceMax: 2099000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 14.1,
    safetyRating: 3.0, // estimated
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Auto AC with Rear Vents", category: "comfort" },
      { name: "14-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "i-SMART Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Jeep",
    model: "Meridian",
    year: 2024,
    priceMin: 2999000,
    priceMax: 3799000,
    bodyType: "SUV",
    fuelType: "DIESEL",
    seatingCapacity: 7,
    mileage: 17.1,
    safetyRating: 3.0, // estimated
    suitedFor: "FAMILY,HIGHWAY_TOURING,OFFROAD",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Hill Descent Control", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "3-Zone Auto AC", category: "comfort" },
      { name: "10.1-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Uconnect Infotainment", category: "tech" },
    ]),
  },
  {
    make: "Toyota",
    model: "Fortuner",
    year: 2024,
    priceMin: 3399000,
    priceMax: 5199000,
    bodyType: "SUV",
    fuelType: "DIESEL",
    seatingCapacity: 7,
    mileage: 12.7,
    safetyRating: 3.0, // estimated
    suitedFor: "OFFROAD,FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "7 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Start Assist", category: "safety" },
      { name: "Disc Brakes All Round", category: "safety" },
      { name: "Leather Seats", category: "comfort" },
      { name: "Auto AC with Rear Vents", category: "comfort" },
      { name: "Power Adjustable Driver Seat", category: "comfort" },
      { name: "9-inch Touchscreen", category: "tech" },
      { name: "JBL Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Hyundai",
    model: "Tucson",
    year: 2024,
    priceMin: 2999000,
    priceMax: 3399000,
    bodyType: "SUV",
    fuelType: "DIESEL",
    seatingCapacity: 5,
    mileage: 14.6,
    safetyRating: 3.0, // estimated
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Leather Seats", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Bose Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "BlueLink Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Kia",
    model: "Carnival",
    year: 2024,
    priceMin: 2499000,
    priceMax: 3399000,
    bodyType: "MUV",
    fuelType: "DIESEL",
    seatingCapacity: 7,
    mileage: 14.2,
    safetyRating: 3.0, // estimated
    suitedFor: "FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Blind Spot Monitor", category: "safety" },
      { name: "Captain Seats with Ottoman", category: "comfort" },
      { name: "3-Zone Auto AC", category: "comfort" },
      { name: "Power Sliding Doors", category: "comfort" },
      { name: "12.3-inch Touchscreen", category: "tech" },
      { name: "Bose Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Rear Seat Entertainment", category: "tech" },
    ]),
  },
  {
    make: "BMW",
    model: "3 Series",
    year: 2024,
    priceMin: 4990000,
    priceMax: 6390000,
    bodyType: "SEDAN",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 16.13,
    safetyRating: 3.0, // estimated
    suitedFor: "HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Leather Sport Seats", category: "comfort" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "12.3-inch Digital Cockpit", category: "tech" },
      { name: "Harman Kardon Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "BMW Connected Drive", category: "tech" },
      { name: "Gesture Control", category: "tech" },
    ]),
  },
  {
    make: "Tata",
    model: "Nexon EV Max",
    year: 2024,
    priceMin: 1699000,
    priceMax: 1949000,
    bodyType: "SUV",
    fuelType: "ELECTRIC",
    seatingCapacity: 5,
    mileage: 437, // km/charge, not kmpl — EV range figure, scorer normalizes within fuel type
    safetyRating: 5.0, // GNCAP tested (Nexon EV, 5-star adult)
    suitedFor: "CITY_COMMUTE,FAMILY",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "Auto AC", category: "comfort" },
      { name: "12.3-inch Touchscreen", category: "tech" },
      { name: "JBL Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Connected Car Tech", category: "tech" },
    ]),
  },
  {
    make: "MG",
    model: "ZS EV",
    year: 2024,
    priceMin: 1898000,
    priceMax: 2598000,
    bodyType: "SUV",
    fuelType: "ELECTRIC",
    seatingCapacity: 5,
    mileage: 461, // km/charge, not kmpl — EV range figure, scorer normalizes within fuel type
    safetyRating: 5.0, // GNCAP tested (global-spec ZS EV, 5-star adult)
    suitedFor: "CITY_COMMUTE,FAMILY",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ADAS Level 1", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Auto AC", category: "comfort" },
      { name: "10.1-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "i-SMART Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "BYD",
    model: "Atto 3",
    year: 2024,
    priceMin: 2099000,
    priceMax: 2199000,
    bodyType: "SUV",
    fuelType: "ELECTRIC",
    seatingCapacity: 5,
    mileage: 521, // km/charge, not kmpl — EV range figure, scorer normalizes within fuel type
    safetyRating: 5.0, // GNCAP tested (Euro NCAP global-spec, 5-star adult)
    suitedFor: "CITY_COMMUTE,FAMILY,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Auto AC", category: "comfort" },
      { name: "12.8-inch Rotating Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Connected Car Tech", category: "tech" },
      { name: "OTA Updates", category: "tech" },
    ]),
  },
  {
    make: "Mahindra",
    model: "Thar Roxx",
    year: 2024,
    priceMin: 1249000,
    priceMax: 2199000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 15.1,
    safetyRating: 5.0, // GNCAP tested (Thar Roxx, 5-star adult, 2024)
    suitedFor: "OFFROAD,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "7 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Hold and Descent Control", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Auto AC", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Adventure Statistics Display", category: "tech" },
    ]),
  },
  {
    make: "Maruti Suzuki",
    model: "Fronx",
    year: 2024,
    priceMin: 749000,
    priceMax: 1329000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 21.5,
    safetyRating: 3.0, // Bharat NCAP tested (3-star adult, 2024)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Hold Control", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Head-Up Display", category: "comfort" },
      { name: "9-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "360 Camera", category: "tech" },
    ]),
  },
  {
    make: "Mahindra",
    model: "Scorpio-N",
    year: 2024,
    priceMin: 1399000,
    priceMax: 2499000,
    bodyType: "SUV",
    fuelType: "DIESEL",
    seatingCapacity: 7,
    mileage: 15.0,
    safetyRating: 5.0, // GNCAP tested (Scorpio-N, 5-star adult, 2022)
    suitedFor: "FAMILY,OFFROAD,HIGHWAY_TOURING",
    featuresJson: JSON.stringify([
      { name: "7 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Hill Hold and Descent Control", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "3-Zone Auto AC", category: "comfort" },
      { name: "12.3-inch Touchscreen", category: "tech" },
      { name: "Sony Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Tata",
    model: "Altroz",
    year: 2024,
    priceMin: 699000,
    priceMax: 999000,
    bodyType: "HATCHBACK",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 19.0,
    safetyRating: 5.0, // GNCAP tested (Altroz, 5-star adult, 2020)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ISOFIX Mounts", category: "safety" },
      { name: "Manual AC", category: "comfort" },
      { name: "Height Adjustable Driver Seat", category: "comfort" },
      { name: "7-inch Touchscreen", category: "tech" },
      { name: "Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Hyundai",
    model: "Exter",
    year: 2024,
    priceMin: 599000,
    priceMax: 999000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 19.4,
    safetyRating: 3.0, // Bharat NCAP tested (3-star adult, 2023)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Rear Parking Camera", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "8-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "BlueLink Connected Tech", category: "tech" },
    ]),
  },
  {
    make: "Kia",
    model: "Sonet",
    year: 2024,
    priceMin: 799000,
    priceMax: 1399000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 18.4,
    safetyRating: 3.0, // estimated
    suitedFor: "CITY_COMMUTE,FIRST_CAR,FAMILY",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Sunroof", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Bose Sound System", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Renault",
    model: "Kiger",
    year: 2024,
    priceMin: 649000,
    priceMax: 1099000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 19.0,
    safetyRating: 4.0, // GNCAP tested (Kiger, 4-star adult)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "Rear Parking Sensors", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "8-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "Nissan",
    model: "Magnite",
    year: 2024,
    priceMin: 599000,
    priceMax: 1249000,
    bodyType: "SUV",
    fuelType: "PETROL",
    seatingCapacity: 5,
    mileage: 19.8,
    safetyRating: 4.0, // GNCAP tested (Magnite, 4-star adult)
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "8-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
    ]),
  },
  {
    make: "MG",
    model: "Comet EV",
    year: 2024,
    priceMin: 699000,
    priceMax: 999000,
    bodyType: "HATCHBACK",
    fuelType: "ELECTRIC",
    seatingCapacity: 4,
    mileage: 230, // km/charge, not kmpl — EV range figure, scorer normalizes within fuel type
    safetyRating: 2.0, // estimated
    suitedFor: "CITY_COMMUTE,FIRST_CAR",
    featuresJson: JSON.stringify([
      { name: "Dual Airbags", category: "safety" },
      { name: "ABS with EBD", category: "safety" },
      { name: "Auto AC", category: "comfort" },
      { name: "10.25-inch Touchscreen", category: "tech" },
      { name: "Wireless Android Auto/CarPlay", category: "tech" },
      { name: "Connected Car Tech", category: "tech" },
    ]),
  },
  {
    make: "Hyundai",
    model: "Ioniq 5",
    year: 2024,
    priceMin: 4600000,
    priceMax: 4700000,
    bodyType: "SUV",
    fuelType: "ELECTRIC",
    seatingCapacity: 5,
    mileage: 631, // km/charge, not kmpl — EV range figure, scorer normalizes within fuel type
    safetyRating: 5.0, // GNCAP/Euro NCAP tested (Ioniq 5, 5-star adult)
    suitedFor: "FAMILY,HIGHWAY_TOURING,CITY_COMMUTE",
    featuresJson: JSON.stringify([
      { name: "6 Airbags", category: "safety" },
      { name: "ESC", category: "safety" },
      { name: "ADAS Level 2", category: "safety" },
      { name: "360 Camera", category: "safety" },
      { name: "Ventilated Front Seats", category: "comfort" },
      { name: "Relaxation Seats with Ottoman", category: "comfort" },
      { name: "Panoramic Sunroof", category: "comfort" },
      { name: "Dual 12.3-inch Screens", category: "tech" },
      { name: "Meridian Sound System", category: "tech" },
      { name: "Vehicle-to-Load (V2L) Charging", category: "tech" },
      { name: "Over-the-Air Updates", category: "tech" },
    ]),
  },
];

async function main() {
  // Idempotency: without this, re-running `prisma db seed` (which also runs
  // automatically after `prisma migrate dev`) inserts a fresh cuid() for every
  // car each time, silently duplicating the whole dataset. Clearing first
  // means this script is always safe to re-run.
  const { count } = await prisma.car.deleteMany();
  if (count > 0) {
    console.log(`Cleared ${count} existing car(s).`);
  }

  console.log(`Seeding ${cars.length} cars...`);
  for (const car of cars) {
    await prisma.car.create({ data: car });
  }
  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
